package model.unit.trait;

public enum UnitTraits {
	NO_MELEE,

	NO_DEFENSIVE_BONUS, // TODO
	NO_TERRAIN_COST,

	BONUS_VS_MOUNTED, // phase 2 TODO
	BONUS_VS_CITY,
	BONUS_VS_TANK, // phase 2 TODO

	PENALTY_VS_CITIES,
	ROUGH_TERRAIN_PENALTY,

	CAN_SETTLE,
	CAN_CREATE_AND_REPAIR,
	INDIRECT_FIRE,
	MOVE_AFTER_ATTACK, // TODO
	LIMITED_VISIBILITY,
	NEED_SETUP
}
