package view.components.GameVisualUI;

public enum UIStates {
    CITY_INFO,
    UNIT_MOVE,
    UNIT_SLEEP,
    UNIT_ALERT,
    UNIT_FORTIFY,
    UNIT_GARRISON,
    UNIT_MELEE_ATTACK,
    CITY_ATTACK,
    UNIT_FORTIFY_UNTIL_HEEL,
    UNIT_RANGED_ATTACK,
    UNIT_PILLAGE,
    UNIT_FOUND_CITY,
    UNIT_CANCEL,
    UNIT_WAKE,
    UNIT_DELETE,
    TILE_INFO,
    UNIT_BUILD_ROAD,
    UNIT_BUILD_RAILROAD,
    REPAIR,
    REMOVE,
    NONE
}
